// Date: 16.2.2012 23:13:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.xcompwiz.mystcraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.entity.Entity;

public class ModelLectern extends ModelBase {
	ModelRendererAdvanced	base;

	public ModelLectern() {
		textureWidth = 64;
		textureHeight = 32;

		base = new ModelRendererAdvanced(this);
		base.setTextureOffset(0, 0);
		base.addElement(new ModelPrism(base, 0, 0, -8, -0.5F, -8, 16, 1, 7, 16, 0));
		base.addElement(new ModelBox(base, 32, 2, -8, -0.5F, -7, 1, 2, 14, 0));
		base.setRotationPoint(0F, 0.5F, 0F);
		base.setTextureSize(64, 32);
		base.mirror = false;
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		base.render(f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
